language: node_js
node_js:
  - "stable"
env:
  - CXX=g++-4.8
before_script:
  - npm install -g eslint eslint-config-google
script: npm run lint
notifications:
  email: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
